language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django==1.4"
  - DJANGO="Django==1.5"
  - DJANGO="Django==1.6"
  - DJANGO="https://www.djangoproject.com/download/1.7b3/tarball/"
matrix:  # see https://docs.djangoproject.com/en/dev/faq/install/
  exclude:
    - python: "3.2"
      env: DJANGO="Django==1.4"
    - python: "3.3"
      env: DJANGO="Django==1.4"
    - python: "3.4"
      env: DJANGO="Django==1.4"
# command to install dependencies
install: 
  - pip install $DJANGO
  - pip install coveralls
  - python setup.py develop
script: coverage run example/manage.py test -v2
after_success:
  - coveralls
