language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION="1.4"
  - DJANGO_VERSION="1.5"
  - DJANGO_VERSION="1.6"
matrix:  # see https://docs.djangoproject.com/en/dev/faq/install/
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION="1.4"
    - python: "3.3"
      env: DJANGO_VERSION="1.4"
# command to install dependencies
install: 
  - pip install Django==$DJANGO_VERSION --use-mirrors
  - pip install coveralls --use-mirrors
  - python setup.py develop
script: coverage run example/manage.py test -v2
after_success:
  - coveralls
