language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
# command to install dependencies
install: 
    - pip install -r requirements.txt --use-mirrors
    - pip install Django==$DJANGO_VERSION --use-mirrors
    - python setup.py develop
script: python example/manage.py test -v2
