language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django==1.4.20"
  - DJANGO="Django==1.5.12"
  - DJANGO="Django==1.6.11"
  - DJANGO="Django==1.7.8"
  - DJANGO="Django==1.8.2"
matrix:  # see https://docs.djangoproject.com/en/dev/faq/install/
  exclude:
    - python: "2.6"
      env: DJANGO="Django==1.7.8"
    - python: "2.6"
      env: DJANGO="Django==1.8.2"
    - python: "3.2"
      env: DJANGO="Django==1.4.20"
    - python: "3.3"
      env: DJANGO="Django==1.4.20"
    - python: "3.4"
      env: DJANGO="Django==1.4.20"
# command to install dependencies
install:
  - pip install $DJANGO
  - pip install coveralls
  - python setup.py develop
script: coverage run example/manage.py test -v2
after_success:
  - coveralls
